### PR TITLE
Issue1

### PR DESCRIPTION
**Pull request by stutisk**

### CODE REVIEW

**Review by abhij1607 — COMMENTED** [review]
Well-Structured Code! Good Practices followed
Fine to merge

**Review by RakshithBhat03 — APPROVED** [review]
Everything looks good. Clean code and good code structure. Good to merge

**Review by ZuberDunge — APPROVED** [review]
Everything looks fine. Good to go from my side.

**Review by shuklahimanshu81 — APPROVED** [review]
Good use of inline comments. Everything looks good to me. Green light from my side

**Pull request merged**
